Using jetty with extra war for integration test
Open problem: Cannot run 'mvn install' from master build dir, because
in that case jetty can't load a class:
2012-05-27 17:21:48.348::WARN:  Nested in
javax.naming.NoInitialContextException: Cannot instantiate class:
org.apache.naming.java.javaURLContextFactory [Root exception is
java.lang.ClassNotFoundException: org.apache.naming.java.javaURLContextFactory]:
java.lang.ClassNotFoundException: org.apache.naming.java.javaURLContextFactory
    at
org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at
org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)